language: python

dist: trusty
sudo: required

services:
  - docker

matrix:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=py27
    - python: "3.5"
      env:
        - TOX_ENV=py35
    - env:
        - DOCKER_COMPOSE_VERSION=1.10.0
      install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +rx docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - docker build . -t internap/fake-switches:latest
        - docker-compose up -d
        - docker inspect -f {{.State.Running}} fakeswitches_tor1.yul1.example.net_1

addons:
  apt:
    packages:
    - telnet

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script: 
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: PeFEYDv8H00aCYsRTkB7L1qxq79VSYny/A0/BD2j309NMQg8Hx1M9AZjophgbsOVDE7t8aE5mcof7M5Ci0KDxOVsN8raCJ9nK1PYyamUq0CuSomohk4EKqK67983yofwBgsywwz991C8ud4lTzVlOo/Tg8Eao0lKCdg/UPdj6vim/PlWQR2h5Vd7CkPwMDMXLFh7SkJo9vmJ7qGSm2ycHSJYE12/mXPoZkmdWQ47BsJ2eQSXtO/N3EodzvC6H9fyg8Fs3Y1RgQETt+MfGtvnuWhj4swO39zboSTWyAeG7O4zbZpPED+71Wl9GEVX7X5V0BxqDtlTdYKBLoIBlQMl0LS+UhujXvTt9E/+Uv2fbUX7hbtsEuUR43E7ilFmNdCffp1OmotGPq3SxT82ILFTSYOCLFFIqY1AhjCe2YFm6JQrb2gmkCbLa/WzU21vHQX//kG+QBvSP+0vVK/TpZCq0XeZicrSVoH1gPHe4egRNHiM1iwNsAcu+LerMvq6+a/JifagnJCWAYVawUYGbBaLxTcp6zyijkejI9Z013JMC5du4+KWHWhE9uQO+vqTyrkmd0SkxiVz6GTae2UHCVInBKlkzJ8J92wLbkAiWeiPadKd1MKbmoHzzP7vWkkOEjOPNHAq4Bcrm329ALsYjK1QijzabwFd7yg0MZ1OaM25/00=
  on:
    tags: true
    python: 2.7
